# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20181122_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='details',
        ),
    ]
