# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20181122_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='issue_type',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6),
        ),
    ]
