# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20181122_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='issue_type',
            field=models.CharField(choices=[('Free', 'FREE'), ('Upgrade', 'UPGRADE')], default='Free', max_length=6),
        ),
    ]
