# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20181122_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='issue_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Upgrade', 'Upgrade')], default='Free', max_length=7),
        ),
    ]
